apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection-engine
  labels:
    app: fraud-detection-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-detection-engine
  template:
    metadata:
      labels:
        app: fraud-detection-engine
    spec:
      imagePullSecrets:
      - name: acr-registry-secret
      containers:
      - name: fraud-detection-engine
        image: crpi-zb9l0odmy4zwf14t-vpc.cn-hangzhou.personal.cr.aliyuncs.com/fraud/fraud-detection-engine:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: fraud-detection-engine-config
              key: server.port
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: fraud-detection-engine-config
              key: spring.profiles.active
        - name: JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: fraud-detection-engine-java-opts
              key: JAVA_OPTS
        - name: FRAUD_THRESHOLD_AMOUNT
          valueFrom:
            configMapKeyRef:
              name: fraud-detection-engine-config
              key: fraud.threshold.amount
        - name: FRAUD_CHECK_SUSPICIOUS_IP
          valueFrom:
            configMapKeyRef:
              name: fraud-detection-engine-config
              key: fraud.check.suspicious.ip
        - name: NOTIFICATION_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: fraud-detection-engine-config
              key: notification.service.url
        - name: NOTIFICATION_SERVICE_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: fraud-detection-engine-config
              key: notification.service.endpoint
        - name: NOTIFICATION_SERVICE_ENABLED
          valueFrom:
            configMapKeyRef:
              name: fraud-detection-engine-config
              key: notification.service.enabled
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
          valueFrom:
            configMapKeyRef:
              name: fraud-detection-engine-config
              key: management.endpoints.web.exposure.include
        - name: SPRING_RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-cloud-config
              key: rabbitmq.host
        - name: SPRING_RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-cloud-config
              key: rabbitmq.port
        - name: SPRING_RABBITMQ_VIRTUAL_HOST
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-cloud-config
              key: rabbitmq.virtualHost
        - name: SPRING_RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq-cloud-credentials
              key: username
        - name: SPRING_RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-cloud-credentials
              key: password
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-engine
spec:
  selector:
    app: fraud-detection-engine
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP 