apiVersion: apps/v1
kind: Deployment
metadata:
  name: notify-service
  labels:
    app: notify-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notify-service
  template:
    metadata:
      labels:
        app: notify-service
    spec:
      imagePullSecrets:
      - name: acr-registry-secret
      containers:
      - name: notify-service
        image: crpi-zb9l0odmy4zwf14t-vpc.cn-hangzhou.personal.cr.aliyuncs.com/fraud/notify-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: notify-service-config
              key: server.port
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: notify-service-config
              key: spring.profiles.active
        - name: JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: notify-service-java-opts
              key: JAVA_OPTS
        - name: NOTIFICATION_EMAIL_ENABLED
          valueFrom:
            configMapKeyRef:
              name: notify-service-config
              key: notification.email.enabled
        - name: NOTIFICATION_SMS_ENABLED
          valueFrom:
            configMapKeyRef:
              name: notify-service-config
              key: notification.sms.enabled
        - name: FRAUD_ENGINE_URL
          valueFrom:
            configMapKeyRef:
              name: notify-service-config
              key: fraud.engine.url
        - name: FRAUD_ENGINE_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: notify-service-config
              key: fraud.engine.endpoint
        - name: SPRING_LIFECYCLE_TIMEOUT_PER_SHUTDOWN_PHASE
          valueFrom:
            configMapKeyRef:
              name: notify-service-config
              key: spring.lifecycle.timeout.per.shutdown.phase
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
          valueFrom:
            configMapKeyRef:
              name: notify-service-config
              key: management.endpoints.web.exposure.include
        - name: SPRING_RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-cloud-config
              key: rabbitmq.host
        - name: SPRING_RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-cloud-config
              key: rabbitmq.port
        - name: SPRING_RABBITMQ_VIRTUAL_HOST
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-cloud-config
              key: rabbitmq.virtualHost
        - name: SPRING_RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq-cloud-credentials
              key: username
        - name: SPRING_RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-cloud-credentials
              key: password
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: notify-service
spec:
  selector:
    app: notify-service
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP 