apiVersion: apps/v1
kind: Deployment
metadata:
  name: tran-integrator
  labels:
    app: tran-integrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tran-integrator
  template:
    metadata:
      labels:
        app: tran-integrator
    spec:
      imagePullSecrets:
      - name: acr-registry-secret
      containers:
      - name: tran-integrator
        image: crpi-zb9l0odmy4zwf14t-vpc.cn-hangzhou.personal.cr.aliyuncs.com/fraud/tran-integrator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: tran-integrator-config
              key: server.port
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: tran-integrator-config
              key: spring.profiles.active
        - name: JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: tran-integrator-java-opts
              key: JAVA_OPTS
        - name: FRAUD_DETECTION_URL
          valueFrom:
            configMapKeyRef:
              name: tran-integrator-config
              key: fraud.detection.url
        - name: FRAUD_DETECTION_CONNECT_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: tran-integrator-config
              key: fraud.detection.connect.timeout
        - name: FRAUD_DETECTION_READ_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: tran-integrator-config
              key: fraud.detection.read.timeout
        - name: SPRING_LIFECYCLE_TIMEOUT_PER_SHUTDOWN_PHASE
          valueFrom:
            configMapKeyRef:
              name: tran-integrator-config
              key: spring.lifecycle.timeout.per.shutdown.phase
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
          valueFrom:
            configMapKeyRef:
              name: tran-integrator-config
              key: management.endpoints.web.exposure.include
        - name: SPRING_RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-cloud-config
              key: rabbitmq.host
        - name: SPRING_RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-cloud-config
              key: rabbitmq.port
        - name: SPRING_RABBITMQ_VIRTUAL_HOST
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-cloud-config
              key: rabbitmq.virtualHost
        - name: SPRING_RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq-cloud-credentials
              key: username
        - name: SPRING_RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-cloud-credentials
              key: password
        - name: RABBITMQ_QUEUE_NAME
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-cloud-config
              key: rabbitmq.queue.name
        - name: RABBITMQ_EXCHANGE_NAME
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-cloud-config
              key: rabbitmq.exchange.name
        - name: RABBITMQ_ROUTING_KEY
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-cloud-config
              key: rabbitmq.routing.key
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8082
          initialDelaySeconds: 60
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: tran-integrator
spec:
  selector:
    app: tran-integrator
  ports:
  - port: 8082
    targetPort: 8082
  type: ClusterIP 